### ISSUE TITLE
NIP-05 challenge

### ISSUE THREAD

**Issue by RobOK2050** [monlovesmango/astral#106]
Set up a nostr.json on a custom subdomain (i.e., not using one of the services). I admittedly had some missteps, i did not originally have the Hex of my public key.

I am now verified on Damus, but in Astral it says Failed to verify NIP05 identifier on the server. I suspect either the mixed case or it being on a subdomain.

**Comment by monlovesmango** [comment]
hey there, can you provide your pubkey or your nip05?

**Comment by RobOK2050** [comment]
Here you go!
RobOK@nostr.technodharma.com
npub1j4cdpp4khf8uc343rtmj6qsyflvnzgntrp6gwg4wden5p6efqhsqvqxzuf

**Comment by monlovesmango** [comment]
hey, so the name listed in the nostr.json file needs to be lowercase. see the spec for nip05: https://github.com/nostr-protocol/nips/blob/master/05.md

**Comment by RobOK2050** [comment]
I don’t think it clearly says that - it says local part should be, which is the part the client is sending. It also says case insensitive , maybe it means case sensitive?

I will update my file, but fyi Damus processed it fine, so there seems to be some ambiguity in the spec.

Thanks for your work on Nostr clients!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by monlovesmango** [comment]
its working on Damus because Damus probably is not messing with the case. I have been lowercasing all my nip05 queries because nostr-tools (the library I am using) was only supporting lowercase queries. But looks like there was a recent update that now supports uppercase as well, so I will update astral to the latest version and stop lowercasing nip05 queries.

**Comment by monlovesmango** [comment]
hey @RobOK2050 your nip05 is now working on astral
