### ISSUE TITLE
On small screens, 1st and 5th button are both "profile"

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#17]
1st and 5th button are redundant I think.

![Screenshot from 2022-06-01 11-08-01](https://user-images.githubusercontent.com/96378/171437557-0f96dcb7-1499-43d9-a34f-57215c09a6d8.png)

**Comment by monlovesmango** [comment]
yeah they are. its like this on all screens (not just small). I couldn't decide which one I wanted to get rid of so just kept both since everything still fits fine. I like the pic bc its personalized and adds symmetry to the new post button, but for users who don't have an icon set its not intuitive that the default one represents their profile. thoughts?

**Comment by Giszmo** [comment]
I would vote to drop the 5th button.

For some strange reason right now my astral 5th button navigates to /undefined.

**Comment by monlovesmango** [comment]
agree. the dup profile button has been removed
