### ISSUE TITLE
image rendering is broken

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#60]
![Screenshot from 2022-11-22 18-14-56](https://user-images.githubusercontent.com/96378/203422554-aaab9e2e-8f95-4f3d-af5e-16c59ef6a97d.png)

The content is actually:

```
"content": "https://mikedilger.com/gossip.png\nhttps://mikedilger.com/gossip.png",
```

**Comment by monlovesmango** [comment]
oh nice catch. conveniently enough, I already inadvertently fixed this (working on a different image inline issue) in my dev version. images are still broken bc of cors, but at least it correctly parses that 2 images are inlined

![image](https://user-images.githubusercontent.com/96307647/203618880-7d9f8ffe-a110-4950-836e-56cda897ad34.png)

will let you know when this is fixed in prod

**Comment by monlovesmango** [comment]
this is fixed now (not the cors part, just the image rendering)

https://astral.ninja/event/57cad47b775a0141376d86b2e242d95535abf47cd0b2329678bff21007add95f
