### ISSUE TITLE
Please explain what these left-up-right navigation buttons are

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#7]
![Screenshot from 2022-05-29 22-39-17](https://user-images.githubusercontent.com/96378/170907296-c4ad7cfe-d36d-46b1-bd11-78f36e5b8cc1.png)

These controls sometimes do something but not always and I don't fully understand where they get me when they do something?

Also the free positioning is ... awkward.

**Comment by monlovesmango** [comment]
hehe, they are back, scroll to top, and forward. for me they work very reliably (since they are using vue router to implement back/forward). and while I don't deny its a bit awkward, I actually love the free positioning feature and find these nav buttons really convenient. so I'm gonna keep them as is at least for now.

however I do agree that tooltips would be nice. I have added these now. are you ok closing this one?

**Comment by Giszmo** [comment]
So sometimes it's only two buttons which makes a different button jump into the place of the one one was hovering over. That is poor for repeated clicking.

The up button is sometimes gone even when in a direct message chat where scrolling up might make sense.

I would disable buttons instead of hiding them.

**Comment by monlovesmango** [comment]
I agree that disabling would be better than hiding it (as it has tripped me up as well). will update this behavior.

**Comment by monlovesmango** [comment]
middle scroll to top nav button will now be disabled instead of hidden on pages where it isn't used
